sudo: false  # disable sudo for speed up

dist: xenial

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gfortran
  - pip install -U pip

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2019-06-22
  - source $HOME/.cargo/env
  - rustup override set nightly
  - pip install -e .
  - pip install codecov pytest pytest-cov

script:
  - pytest tests --cov=./

after_success:
  - codecov
