sudo: false  # disable sudo for speed up

dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install -U pip

install:
  - pip install -e .
  - pip install codecov pytest pytest-cov

script:
  - pytest tests --cov=./

after_success:
  - codecov
