from enum import IntEnum


class ResultFlag(IntEnum):
    SUCCESS = 0
    HYPOTHESIS_OUT_OF_SERCH_RANGE = -1
    KEY_OUT_OF_RANGE = -2
    REF_OUT_OF_RANGE = -3
    REF_EPIPOLAR_TOO_SHORT = -4
    INSUFFICIENT_GRADIENT = -5
    NEGATIVE_PRIOR_DEPTH = -6
    NEGATIVE_REF_DEPTH = -7
    NOT_PROCESSED = -8
