from enum import IntEnum


class ResultFlag(IntEnum):
    SUCCESS = 0
    HYPOTHESIS_OUT_OF_SERCH_RANGE = -1
    KEY_OUT_OF_RANGE = -2
    REF_CLOSE_OUT_OF_RANGE = -3
    REF_FAR_OUT_OF_RANGE = -4
    REF_EPIPOLAR_TOO_SHORT = -5
    INSUFFICIENT_GRADIENT = -6
    NEGATIVE_PRIOR_DEPTH = -7
    NEGATIVE_REF_DEPTH = -8
    NOT_PROCESSED = -9
